### ISSUE TITLE
ReadmeLogo

### ISSUE THREAD

**Issue by ycoady** [ycoady/UVic-Distributed-Systems#1]
![logods](https://cloud.githubusercontent.com/assets/1288637/5566593/a64ba4bc-8ee2-11e4-8612-28191f82fdd1.png)

**Comment by Hoverbear** [comment]
This isn't an issue, can we close this?

**Comment by ycoady** [comment]
yes!  i thought we might want to get a new logo, but we have enough other stuff to do!!!! :)

**Comment by Hoverbear** [comment]
What, you don't like brightly colored cartoony folks staring at each other on plates with tubes in between!?
